### ISSUE TITLE
Unsupported config option for services.dockergen: 'volumes_from'

### ISSUE THREAD

**Issue by 01BTC10** [tornadocash/tornado-pool-relayer#13]
The docker-compose.yml use "version 3" but it throws an error unless it is changed to "version 2". 

$ docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.dockergen: 'volumes_from'
Unsupported config option for services.letsencrypt: 'volumes_from'

**Comment by dan1kov** [comment]
Fixed in #14. Thank you for reporting the issue.
